# Generated by Django 5.2 on 2025-06-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
